### ISSUE TITLE
src install error

### ISSUE THREAD

**Issue by Paulie-ai** [lujiarui/Str2Str#2]
Hi jiarui, 
   I am trying to create the env providede in env.yaml, but get a error when install src=0.0.1

pip install src==0.0.1
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting src==0.0.1
  Downloading src-0.0.1.zip (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6vdmjax1/src_62c18340b1e54ae7a883b44d67a112fc/setup.py", line 14, in <module>
          long_description = '\n\n'.join([open(f).read() for f in [
        File "/tmp/pip-install-6vdmjax1/src_62c18340b1e54ae7a883b44d67a112fc/setup.py", line 14, in <listcomp>
          long_description = '\n\n'.join([open(f).read() for f in [
      FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Do you meet this error, or know some solution to fixed this problem? Thanks

**Comment by lujiarui** [comment]
Hi, which command do you use to install the local `src` package?

**Comment by Paulie-ai** [comment]
After trying conda env create -f environment.yml show above error, i am using pip install src==0.0.1 and also get error.

**Comment by lujiarui** [comment]
`src` is a local package and is only installed via `pip install -e .` in the root directory

**Comment by Paulie-ai** [comment]
Thanks, i skip src in environment.yml, and no error meet now.
