### ISSUE TITLE
tica plot is not same as Figure S4

### ISSUE THREAD

**Issue by Paulie-ai** [lujiarui/Str2Str#3]
Hello Jiarui, 
    Recently i am using mdtraj to extract 1000 frame as reference, and using sampling 1000 frame for all 12 fast folding protein. Specificly, I am using interval to make microseconds MD data to 1000 frame. But the TICA plot is not even close， I used default eval.py and metrics.py， i am very confused about the reason for this  results. Can you offer some help to this results? Thanks.
[metrics_dev_0318-05-27.csv](https://github.com/lujiarui/Str2Str/files/14651465/metrics_dev_0318-05-27.csv)
![tica_1FME_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/4d6ba685-6541-4cdb-8581-fc76683c5529)
![tica_2F4K_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/6afd8c98-6448-4f0c-aab0-f777fc8a0dec)
![tica_2JOF_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/3eea706d-624d-48d7-ae6c-f5a5ef58b06e)
![tica_2WAV_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/cf291596-ba0c-47a0-8c96-f2e961d51dba)
![tica_A3D_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/ca7e777c-6e0b-4123-ac71-9582f51c233f)
![tica_CLN025_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/1d7324aa-7682-45e3-b348-c1e70051248c)
![tica_GTT_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/3d0026b4-3d8b-4d8a-b71d-5bcb0bf7be91)
![tica_lambda_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/4e51d982-731c-4183-90f5-d268a7469191)
![tica_NTL9_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/03c23e98-1b00-4e28-b1be-606dad8cc921)
![tica_NuG2_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/afa10272-0298-4f50-acd9-1635e684cb74)
![tica_PRB_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/b9a8583d-9d88-4aa9-b583-6bf12ee89fa7)
![tica_UVF_dev_0318-05-27](https://github.com/lujiarui/Str2Str/assets/50875521/9caaa64d-134c-473b-84fe-352527e7d3e4)

**Comment by Zuricho** [comment]
Hi @Paulie-ai , for tICA analysis, we select a trajectory with more samples from D. E. Shaw's trajectories (Science 2011 and Science 2010) to ensure the correctness. For fast-folding proteins, we set stride=50 to get a trajectory with more than 10,000 samples. You can use the following code for you extraction and analysis:
```bash
mdconvert -t [output_pdb] -o [topology file] [trajectories] -s 50
```
1000 samples is not enough for tICA method, and using a lag time 20 could be too high (when using 1000 samples).
