### ISSUE TITLE
Is there any recommended configuration for training Str2Str?

### ISSUE THREAD

**Issue by JinyinZha** [lujiarui/Str2Str#5]
Hi, I am trying to retrain Str2Str, but found a huge consumption of GPU memory, even if batch_size=1. I am asking whether there is a recommended hardware configuration for training Str2str models? Thank you~

**Comment by lujiarui** [comment]
Hi, please refer to [this](https://github.com/lujiarui/Str2Str/issues/4#issuecomment-2050003432). If the problem still present, please let me know and provide with more details. Thanks!

**Comment by JinyinZha** [comment]
Thanks for you reply. In fact, I mean how much memory is enough to train Str2Str? This would help to to choose what GPU or how many GPUs for retraijning the model.

**Comment by lujiarui** [comment]
Our model was trained on 32GB V100 GPUs.

**Comment by JinyinZha** [comment]
Well I found the problem is that some multi-chain proteins are included in training, which could lead to an enormous memory cost. If I remove pkl files larger than 1M, it in fact would could consult 6.7 GB memory when batch_size=1.
